### ISSUE TITLE
macOS fails to build scotch with git branch but succeeds to build with tarball

### ISSUE THREAD

**Issue by tai271828** [solvcon/devenv#101]
When working on https://github.com/solvcon/devenv/issues/98 , which is raised by multiple causes. I realized one of the failure root causes is macOS fail to build scotch with its git branch when succeeding to build with scotch tarball.

You may refer to the result of the CI job run with my branch https://github.com/tai271828/devenv/actions/runs/1766863747

**Comment by tai271828** [comment]
This pull request was created to monitor this kind of issue in the future by adding CI jobs. https://github.com/solvcon/devenv/pull/102

Anyone with macOS is more than welcome to fix this issue and thus able to make all of the CI jobs created by https://github.com/solvcon/devenv/pull/102 pass.

**Comment by yungyuc** [comment]
If a release tarball does not have the issue, we can also switch from master branch to a release.

**Comment by tai271828** [comment]
The fix is landed. If the scheduled CI this week passes, we can close this issue then.

**Comment by yungyuc** [comment]
In https://github.com/yungyuc/devenv/runs/5337852763?check_suite_focus=true#step:4:13 , the `SYNCGIT="yes"` build still fails.  It seems to still use the `master` branch as the directory suggests.

**Comment by tai271828** [comment]
Let's keep this issue open if we want to resolve the issue (build failure with scotch codebase tip). Let's close this issue if we are happy with the release tarball and the corresponding tag branch.

The recent CI job of "build with git" could pass because it tested with the tag branch rather than the codebase tip.

**Comment by yungyuc** [comment]
I don't understand why it succeeds now.  But I don't think we need to spend more time on the tip-vs-tag issue anymore.  Let's close it.

**Comment by yungyuc** [comment]
I figured it out.  The failure was in my fork.  I wrongly took it as the upstream repo.  Nothing to worry about now.
